In [1]:
include("HighDimMixedModels.jl")

Main.HighDimMM

In [2]:
using LinearAlgebra
using DataFrames
using StableRNGs; rng = StableRNG(1);
using StatsModels
using MixedModels
import .HighDimMM   #https://docs.julialang.org/en/v1/manual/variables-and-scoping/

**Set up data and formula, specify factor variables(CategoricalTerm)**

In [3]:
#df = DataFrame(y = rand(rng, 9), a = 1:9, b = rand(rng, 9), c = repeat(["d","e","f"], 3), d = vcat(repeat([1,2], 4),1))
df = DataFrame(y = rand(rng, 9), a = 1:1:9, b = rand(rng, 9), c = repeat(["d","e","f"], 3), d = rand(rng, 9))
f = @formula(y ~  a + b + c + d)
contrasts = Dict(:a => ContinuousTerm, :b=>ContinuousTerm, :c => CategoricalTerm)

Dict{Symbol, UnionAll} with 3 entries:
  :a => ContinuousTerm
  :b => ContinuousTerm
  :c => CategoricalTerm

In [4]:
df

9×5 DataFrame
 Row │ y          a      b         c       d        
     │ Float64    Int64  Float64   String  Float64  
─────┼──────────────────────────────────────────────
   1 │ 0.585195       1  0.236782  d       0.752223
   2 │ 0.0773379      2  0.943741  e       0.314815
   3 │ 0.716628       3  0.445671  f       0.858522
   4 │ 0.320357       4  0.763679  d       0.698713
   5 │ 0.653093       5  0.145071  e       0.757746
   6 │ 0.236639       6  0.021124  f       0.419294
   7 │ 0.709684       7  0.152545  d       0.412607
   8 │ 0.557787       8  0.617492  e       0.454589
   9 │ 0.05079        9  0.481531  f       0.380933

In [ ]:
## https://stackoverflow.com/questions/28756206/julia-converting-column-type-from-integer-to-float64-in-a-dataframe
df[:,:a] = convert(Vector{Float64},df[:,2]) # assign vector values and convert them into Int64
df[!,:a] = convert(Vector{Float64},df[:,2]) # change the vector reference to the vector with float64

In [ ]:
for i in 1:size(df,2)
    if(eltype(df[:,i]) == Int64)
        println("y")
        df[!,i] = convert(Vector{Float64},df[:,i])
    end
end

In [ ]:
df

In [ ]:
f

**try for f2**

In [20]:
# try for f2
f2 = @formula(y ~ 1 + a + b + (1|c))

FormulaTerm
Response:
  y(unknown)
Predictors:
  1
  a(unknown)
  b(unknown)
  (c)->1 | c

In [21]:
sch = MixedModels.schema(f2,df,contrasts)

StatsModels.Schema with 4 entries:
  c => c
  b => b
  a => a
  y => y


In [22]:
form = MixedModels.apply_schema(f2, sch, LinearMixedModel)

FormulaTerm
Response:
  y(continuous)
Predictors:
  1
  a(continuous)
  b(continuous)
  (1 | c)

In [23]:
form = MixedModels.apply_schema(f2, sch, HighDimMM.highDimMixedModel)

FormulaTerm
Response:
  y(continuous)
Predictors:
  1
  a(continuous)
  b(continuous)
  (c)->1 | c

In [ ]:
form = apply_schema(f2, sch)

In [ ]:
?apply_schema

In [24]:
typeof(LinearMixedModel)

UnionAll

In [25]:
typeof(HighDimMM.highDimMixedModel)

UnionAll

**back here**

In [ ]:
sch = MixedModels.schema(f,df,contrasts)

In [ ]:
form.rhs.terms[[2,3]]

In [ ]:
form = apply_schema(f, sch)

In [ ]:
typeof(form)

In [ ]:
names(df)

In [ ]:
findall(x -> x == "a", names(df))

In [ ]:
if typeof(["a","b"]) == Array{String, 1}
    println("123")
else
    println("456")
end

In [ ]:
typeof(["a","b"])

In [ ]:
form.rhs.terms[[1,2]]

In [ ]:
modelcols(form.rhs.terms[[2,4]],df)

In [ ]:
modelcols(form.rhs.terms[1],df)

In [ ]:
Vector<:AbstractVector

In [ ]:
AbstractVecOrMat

In [ ]:
Vector(1:length(form.rhs.terms))

In [ ]:
[1,2]

In [ ]:
df[:,["b","c"]]

In [ ]:
y,pred = modelcols(form, df);

In [ ]:
y

In [ ]:
pred

In [ ]:
pred = modelmatrix(form, df);

In [ ]:
pred

In [ ]:
typeof(pred)

### Number of variables indicates M,X,Z

In [ ]:
HMM = HighDimMM.highDimMixedModel(f, df, contrasts, 1, 1)

In [ ]:
# Three matrix
HMM.M.M; HMM.X.X; HMM.Z.Z

### indices indicates M,X,Z

In [ ]:
include("HighDimMixedModels.jl")

In [ ]:
HMM = HighDimMM.highDimMixedModel(f, df, contrasts, 1, [2,4],3)

In [ ]:
Matrix{Int64}<:AbstractVecOrMat{AbstractFloat}

In [ ]:
Matrix{Int64}<:AbstractVecOrMat{<:Number}

In [ ]:
[1.0 2.3; 2.0 4.9]::AbstractVecOrMat{Float64}

In [ ]:
Matrix<:AbstractVecOrMat

In [ ]:
HMM.M.M

In [ ]:
HMM.X.X

In [ ]:
HMM.M.M * HMM.X.X

In [ ]:
# response
y = HMM.y

## variable names indicates M,X,Z

In [5]:
include("HighDimMixedModels.jl")

Main.HighDimMM

In [6]:
HMM = HighDimMM.highDimMixedModel(f, df, contrasts, "a", ["b","d"],"c")

┌ Warning: n >= p in high dimensional matrix
└ @ Main.HighDimMM /Users/zyxu/Documents/julia/highDimMM/bricks.jl:12


Main.HighDimMM.highDimMixedModel{Float64}(y ~ a + b + c + d, Main.HighDimMM.highDimMat{Float64, Matrix{Float64}}([1.0; 2.0; … ; 8.0; 9.0]), Main.HighDimMM.XMat{Float64, Matrix{Float64}}([0.236781883208121 0.7522231521093703; 0.9437409715735081 0.31481548090434086; … ; 0.617492416565387 0.45458919106592477; 0.48153065407402607 0.38093255230858825]), [0.0 0.0; 1.0 0.0; … ; 1.0 0.0; 0.0 1.0], [0.5851946422124186, 0.07733793456911231, 0.7166282400543453, 0.3203570514066232, 0.6530930076222579, 0.2366391513734556, 0.7096838914472361, 0.5577872440804086, 0.05079002172175784])

In [7]:
HMM.M.M

9×1 Matrix{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 7.0
 8.0
 9.0

In [8]:
HMM.X.X

9×2 Matrix{Float64}:
 0.236782  0.752223
 0.943741  0.314815
 0.445671  0.858522
 0.763679  0.698713
 0.145071  0.757746
 0.021124  0.419294
 0.152545  0.412607
 0.617492  0.454589
 0.481531  0.380933

In [9]:
HMM.Z.Z

9×2 Matrix{Float64}:
 0.0  0.0
 1.0  0.0
 0.0  1.0
 0.0  0.0
 1.0  0.0
 0.0  1.0
 0.0  0.0
 1.0  0.0
 0.0  1.0

In [10]:
y = HMM.y

9-element Vector{Float64}:
 0.5851946422124186
 0.07733793456911231
 0.7166282400543453
 0.3203570514066232
 0.6530930076222579
 0.2366391513734556
 0.7096838914472361
 0.5577872440804086
 0.05079002172175784

In [14]:
r = size(HMM.M,2) + size(HMM.X,2)

3

$$
\mathbf{y} \text { is } N_{n}(\mathbf{X} \boldsymbol{\beta}, \mathbf{\Sigma}), \quad \text { where } \quad \mathbf{\Sigma}= \sigma_{z}^{2}
\mathbf{Z} \mathbf{Z}^{\prime}+\sigma^{2} \mathbf{I}_{n} 
$$

Let $$\mathbf{P}=\mathbf{I}-\mathbf{H}=\mathbf{I}-\mathbf{X}\left(\mathbf{X}^{\prime} \mathbf{X}\right)^{-} \mathbf{X}^{\prime}$$

$$\mathbf{K}=\mathbf{C}\mathbf{P} \in R^{(n-r)\times n}$$

$$
Ky \sim N_{n-r}\left(\mathbf{0}, \mathbf{K} \mathbf{\Sigma} \mathbf{K}^{\prime}\right) = N_{n-r}\left[\mathbf{0}, \mathbf{K}\left(\sigma_{z}^{2} \mathbf{Z} \mathbf{Z}^{\prime}+\sigma^{2} \mathbf{I}_{n} \right) \mathbf{K}^{\prime}\right]
$$

To simplify, we assume fixed effect as full rank, where r is the number of fixed effects.

In [12]:
Z = HMM.Z.Z
y = HMM.y

9-element Vector{Float64}:
 0.5851946422124186
 0.07733793456911231
 0.7166282400543453
 0.3203570514066232
 0.6530930076222579
 0.2366391513734556
 0.7096838914472361
 0.5577872440804086
 0.05079002172175784

In [13]:
# A is X in formula
A = hcat(HMM.M.M, HMM.X.X)
P = I - A*inv(transpose(A)*A)*transpose(A)
u,s,v = svd(P)
C = transpose(u[:,1:4]) # simplify: assume fixed effect full rank
K = C*P

4×9 Matrix{Float64}:
  8.85863e-18  -0.437769    0.0614729  …   0.417562  -0.118552   0.0472971
 -0.794874     -0.0213923   0.417183      -0.031295  -0.124852  -0.198574
 -1.68935e-17  -0.321258    0.479844      -0.551886   0.280829   0.243072
  8.20796e-17  -0.252174   -0.184915      -0.382227   0.017293   0.448349

In [18]:
n = size(HMM.M, 1)
A = hcat(HMM.M.M, HMM.X.X)
P = I - A*inv(transpose(A)*A)*transpose(A)
u,s,v = svd(P)
r = size(HMM.M,2) + size(HMM.X,2)  # simplify: assume fixed effect full rank
#C = transpose(u[:,1:(n-r)]) 
C = randn((n-r),n)
K = C*P
Z = HMM.Z.Z
y = HMM.y

9-element Vector{Float64}:
 0.5851946422124186
 0.07733793456911231
 0.7166282400543453
 0.3203570514066232
 0.6530930076222579
 0.2366391513734556
 0.7096838914472361
 0.5577872440804086
 0.05079002172175784

In [19]:
maximum(K*A)

3.774758283725532e-15

In [ ]:
C

The objective function is:
$$
\frac{n-r}{2} \ln (2 \pi)-\frac{1}{2} \ln \left|\mathbf{K} \Sigma \mathbf{K}^{\prime}\right|-\frac{1}{2} \mathbf{y}^{\prime} \mathbf{K}^{\prime}\left(\mathbf{K} \Sigma \mathbf{K}^{\prime}\right)^{-1} \mathbf{K} \mathbf{y}
$$

In [ ]:
using NLopt

In [ ]:
function negLogLik(sigma::Vector{Float64}, g::Vector{Float64})
    n = length(y) 
    Sigma = sigma[1]*Z*transpose(Z) + sigma[2]*diagm(ones(n))
    negLog = -1/2*log(det(K*Sigma*transpose(K))) - 1/2*transpose(y)*transpose(K)*inv(K*Sigma*transpose(K))*K*y
    return negLog
end

In [ ]:
negLogLik([1.0,1.0], [2.0,2.0])

In [ ]:
opt = Opt(:LN_COBYLA, 2)
opt.min_objective = negLogLik
opt.xtol_rel = 1e-5

In [ ]:
sigma = [1,1]
println("OPTBL: starting point $(sigma)")
(optf,optx,ret) = optimize(opt, sigma)
numevals = opt.numevals
println("got $(round(optf, digits=5)) at $(round.(optx, digits=5)) after $numevals iterations (returned $(ret))")

After getting estimate of sigma, we estimate beta
$$
\hat{\beta}(\theta) = (X^T\Sigma^{-1}X)^{-1}X^T\Sigma^{-1}y
$$

In [ ]:
sigma = [1, 1]
n = 9

In [ ]:
Sigma = sigma[1]*Z*transpose(Z) + sigma[2]*diagm(ones(n))

In [ ]:
# A is X in formula
inv(transpose(A)*inv(Sigma)*A)*transpose(A)*inv(Sigma)*y

In [ ]:
using NLopt

function myfunc(x::Vector, grad::Vector)
    if length(grad) > 0
        grad[1] = 0
        grad[2] = 0.5/sqrt(x[2])
    end
    return sqrt(x[2])
end

function myconstraint(x::Vector, grad::Vector, a, b)
    if length(grad) > 0
        grad[1] = 3a * (a*x[1] + b)^2
        grad[2] = -1
    end
    (a*x[1] + b)^3 - x[2]
end

opt = Opt(:LD_MMA, 2)
opt.lower_bounds = [-Inf, 0.]
opt.xtol_rel = 1e-4

opt.min_objective = myfunc
inequality_constraint!(opt, (x,g) -> myconstraint(x,g,2,0), 1e-8)
inequality_constraint!(opt, (x,g) -> myconstraint(x,g,-1,1), 1e-8)

minf,minx,ret = optimize(opt, [1.234, 5.678])
numevals = opt.numevals # the number of function evaluations
println("got $minf at $minx after $numevals iterations (returned $ret)")

In [ ]:
opt.

In [ ]:
function test()
    x = 1+2
    y =  2*x
    z = [1,2]
    return (x,y,z)
end

In [ ]:
test()

In [ ]:
x

In [ ]:
y

### test fit!()

In [ ]:
include("HighDimMixedModels.jl")
HMM = HighDimMM.highDimMixedModel(f, df, contrasts, 1, [2,4],3)

In [ ]:
HighDimMM.fit!(HMM, verbose = true, REML = true)

In [ ]:
HighDimMM.test!(HMM, verbose = true, REML = true)

In [ ]:
n = size(HMM.M, 1)
A = hcat(HMM.M.M, HMM.X.X)
P = I - A*inv(transpose(A)*A)*transpose(A)
u,s,v = svd(P)
r = size(HMM.M,2) + size(HMM.X,2)  # simplify: assume fixed effect full rank
C = transpose(u[:,1:(n-r)]) 
K = C*P
Z = HMM.Z.Z
y = HMM.y

In [ ]:
function negLogLik(sigma::Vector{Float64}, g::Vector{Float64})
    n = length(y)
    Sigma = sigma[1]*Z*transpose(Z) + sigma[2]*diagm(ones(n))
    negLog = -1/2*log(det(K*Sigma*transpose(K))) - 1/2*transpose(y)*transpose(K)*inv(K*Sigma*transpose(K))*K*y
    return negLog
end

In [ ]:
negLogLik([2.0,2.0],[2.0,2.0])

In [ ]:
using NLopt
opt = Opt(:LN_COBYLA, 2) # :GN_DIRECT_L  :LN_COBYLA :LN_BOBYQA
opt.min_objective = negLogLik
opt.xtol_rel = 1e-5

sigma = [2,2]
println("OPTBL: starting point $(sigma)")



In [ ]:
(optf,optx,ret) = optimize(opt, sigma)

In [ ]:
println("got $(round(optf, digits=5)) at $(round.(optx, digits=5)) after $numevals iterations (returned $(ret))") 

In [ ]:
ndims(opt)

In [ ]:
opt.algorithm

In [ ]:
alg = :LN_COBYLA
opt = Opt(alg, 2) # :GN_DIRECT_L  :LN_COBYLA :LN_BOBYQA
opt.min_objective = negLogLik
opt.xtol_rel = 1e-5

sigma = [2,2]
(optf,optx,ret) = optimize(opt, sigma)
println("got $(round(optf, digits=5)) at $(round.(optx, digits=5)) after $numevals iterations (returned $(ret))") 

In [ ]:
algorithm_name(opt::Opt)

In [ ]:
typeof(:LN_COBYLA)