In [3]:
include("HighDimMixedModels.jl")
using LinearAlgebra

$$
 Y = M\alpha + X\beta + Z\theta + \varepsilon
$$

In [ ]:
X = [1 2;3 4]

In [ ]:
#A = highDimMat{Int64, typeof(X)}([1 2;3 4])

In [ ]:
A = HighDimMM.highDimMat([1 2 3 4;3 4 5 6])

In [ ]:
typeof(X)

In [ ]:
typeof(A)

In [ ]:
eltype(A)

In [ ]:
size(A)

In [ ]:
copyto!(A, [1 2 3;3 4 6])

In [ ]:
A.M

In [ ]:
B = HighDimMM.XMat([1 2 3;3 4 5; 0 0 1; 1 0 0])

In [ ]:
size(B)

In [ ]:
rank([1 2 3;3 4 5; 0 0 1; 1 0 0])

In [ ]:
rank(B)

In [ ]:
A*B

In [ ]:
A.M*B.X

In [ ]:
a = [1 2 3; 4 5 6; 7 8 9]

In [ ]:
b = a[:,1]
c = reshape(b, size(b,1),1)

In [ ]:
a

In [ ]:
hcat(c, a)

In [ ]:
a*b

In [ ]:
mul!(a,b)

In [ ]:
?mul!

In [ ]:
+(1,2,3)

HDMM

In [4]:
using DataFrames
using StableRNGs; rng = StableRNG(1);
using StatsModels
#df = DataFrame(y = rand(rng, 9), a = 1:9, b = rand(rng, 9), c = repeat(["d","e","f"], 3), d = vcat(repeat([1,2], 4),1))
df = DataFrame(y = rand(rng, 9), a = 1:9, b = rand(rng, 9), c = repeat(["d","e","f"], 3))
f = @formula(y ~ 1 + a + b + c)
contrasts = Dict(:b=>ContinuousTerm, :c => CategoricalTerm)

Dict{Symbol, UnionAll} with 2 entries:
  :b => ContinuousTerm
  :c => CategoricalTerm

In [5]:
df

9×4 DataFrame
 Row │ y          a      b         c      
     │ Float64    Int64  Float64   String 
─────┼────────────────────────────────────
   1 │ 0.585195       1  0.236782  d
   2 │ 0.0773379      2  0.943741  e
   3 │ 0.716628       3  0.445671  f
   4 │ 0.320357       4  0.763679  d
   5 │ 0.653093       5  0.145071  e
   6 │ 0.236639       6  0.021124  f
   7 │ 0.709684       7  0.152545  d
   8 │ 0.557787       8  0.617492  e
   9 │ 0.05079        9  0.481531  f

In [6]:
HMM = HighDimMM.highDimMixedModel(f, df, contrasts, 1, 1)

┌ Warning: n >= p in high dimensional matrix
└ @ Main.HighDimMM /Users/zyxu/Documents/julia/highDimMM/bricks.jl:12


Main.HighDimMM.highDimMixedModel{Float64}(y ~ 1 + a + b + c, Main.HighDimMM.highDimMat{Float64, Matrix{Float64}}([1.0; 2.0; … ; 8.0; 9.0]), Main.HighDimMM.XMat{Float64, Matrix{Float64}}([1.0 0.236781883208121; 1.0 0.9437409715735081; … ; 1.0 0.617492416565387; 1.0 0.48153065407402607]), [0.0 0.0; 1.0 0.0; … ; 1.0 0.0; 0.0 1.0], [0.5851946422124186, 0.07733793456911231, 0.7166282400543453, 0.3203570514066232, 0.6530930076222579, 0.2366391513734556, 0.7096838914472361, 0.5577872440804086, 0.05079002172175784])

In [7]:
HMM.M.M

9×1 Matrix{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 7.0
 8.0
 9.0

In [8]:
HMM.X.X

9×2 Matrix{Float64}:
 1.0  0.236782
 1.0  0.943741
 1.0  0.445671
 1.0  0.763679
 1.0  0.145071
 1.0  0.021124
 1.0  0.152545
 1.0  0.617492
 1.0  0.481531

In [9]:
HMM.Z.Z

9×2 Matrix{Float64}:
 0.0  0.0
 1.0  0.0
 0.0  1.0
 0.0  0.0
 1.0  0.0
 0.0  1.0
 0.0  0.0
 1.0  0.0
 0.0  1.0

In [10]:
HMM.y

9-element Vector{Float64}:
 0.5851946422124186
 0.07733793456911231
 0.7166282400543453
 0.3203570514066232
 0.6530930076222579
 0.2366391513734556
 0.7096838914472361
 0.5577872440804086
 0.05079002172175784

In [ ]:
push!([5, 2, 3], 4)

In [11]:
A = hcat(HMM.M.M, HMM.X.X)

9×3 Matrix{Float64}:
 1.0  1.0  0.236782
 2.0  1.0  0.943741
 3.0  1.0  0.445671
 4.0  1.0  0.763679
 5.0  1.0  0.145071
 6.0  1.0  0.021124
 7.0  1.0  0.152545
 8.0  1.0  0.617492
 9.0  1.0  0.481531

In [12]:
P = I - A*inv(transpose(A)*A)*transpose(A)

9×9 Matrix{Float64}:
  0.520973   -0.143783     -0.252433    …   0.184977     0.209717
 -0.143783    0.462356     -0.19791        -0.119911    -0.000619957
 -0.252433   -0.19791       0.821592       -0.00353017   0.0264953
 -0.0604651  -0.354986     -0.135189       -0.172444    -0.107198
 -0.213517    0.0581287    -0.11919        -0.0139248   -0.0563311
 -0.184352    0.170105     -0.0888158   …  -0.0283347   -0.102937
 -0.0611175   0.126619     -0.0510196      -0.132019    -0.199864
  0.184977   -0.119911     -0.00353017      0.647698    -0.362512
  0.209717   -0.000619957   0.0264953      -0.362512     0.59325

In [13]:
u,s,v = svd(P)

SVD{Float64, Float64, Matrix{Float64}}
U factor:
9×9 Matrix{Float64}:
  1.34407e-17   0.721784   …   0.587281  -0.358792    -0.0734559
 -0.190676     -0.199205      -0.192051  -0.666302    -0.23833
 -0.0463644    -0.349734       0.209233  -0.3661       0.0245039
  0.0537586    -0.0837717     -0.189029  -0.477457    -0.00231795
  0.648374     -0.295818       0.330352  -0.116465     0.3033
 -0.0637745    -0.255412   …   0.365092  -0.00493805   0.433344
 -0.672223     -0.0846755      0.149638  -0.0221965    0.472749
  0.286397      0.256278      -0.392585  -0.207657     0.393773
 -0.0154922     0.290553      -0.346074  -0.0900704    0.528082
singular values:
9-element Vector{Float64}:
 1.0000000000000002
 1.0
 1.0
 1.0
 1.0
 0.9999999999999999
 1.0555910676597907e-15
 6.102774479646989e-16
 1.0608953044925711e-16
Vt factor:
9×9 Matrix{Float64}:
  0.0       -0.190676   -0.0463644  …  -0.672223    0.286397   -0.0154922
  0.721784  -0.199205   -0.349734      -0.0846755   0.256278    0.290553

In [14]:
u = u[:,1:6]
s = diagm(s[1:6])
v = v[:,1:6]
maximum(u*s*transpose(v) - P)

2.55351295663786e-15

In [15]:
s*transpose(v)

6×9 Matrix{Float64}:
 0.0       -0.190676   -0.0463644  …  -0.672223    0.286397   -0.0154922
 0.721784  -0.199205   -0.349734      -0.0846755   0.256278    0.290553
 0.0       -0.517681    0.0175724      0.0823317   0.0976185  -0.314116
 0.0        0.177124   -0.256386      -0.40938     0.0725489  -0.0347221
 0.0       -0.0397892  -0.15056       -0.155654   -0.696412    0.579134
 0.0       -0.292176    0.780011   …  -0.309793    0.0146294   0.270772

In [17]:
s*transpose(v)*A

6×3 Matrix{Float64}:
 -5.2354e-15   -9.88792e-16  -4.71845e-16
 -4.71845e-15  -8.88178e-16  -3.33067e-16
  5.55112e-16   3.33067e-16   4.44089e-16
  6.38378e-16  -6.93889e-17  -9.71445e-17
 -3.21965e-15  -5.55112e-16  -1.2809e-16
  1.4988e-15    1.66533e-16   5.64184e-18

In [ ]:
K = transpose(u)*P## use this

In [ ]:
transpose(u)*u*s*transpose(v)

In [ ]:
maximum(transpose(u)*P*A)

In [ ]:
K*A

In [18]:
randn(9, 6)

9×6 Matrix{Float64}:
  0.775828  -0.248522   -0.665225   1.38532    1.9676     1.3052
  0.620779  -2.66428    -1.14372   -1.3766     1.69857   -1.81482
 -1.53403   -0.0768283   0.572958  -1.2075    -2.49606    1.53395
  0.358795  -0.348564    0.830155  -0.81888    0.144877  -1.14289
  1.94652   -0.442573    0.872718   0.447337  -0.219622  -0.44091
 -0.121813   2.16696     0.346889   0.679974   0.816193  -1.73046
  0.847584   0.0690022  -1.41354    0.287173  -0.334161   0.368597
  1.21918   -0.851399   -0.837109  -1.66663   -0.510076  -1.68946
 -1.42896    0.534756   -0.584069  -0.199521  -1.78439   -1.38653

In [19]:
u[:,1:6]

9×6 Matrix{Float64}:
  1.34407e-17   0.721784   -4.77891e-17  …   1.67262e-16  -1.19473e-17
 -0.190676     -0.199205   -0.517681        -0.0397892    -0.292176
 -0.0463644    -0.349734    0.0175724       -0.15056       0.780011
  0.0537586    -0.0837717   0.764194         0.344961     -0.151601
  0.648374     -0.295818   -0.175161         0.10984      -0.336347
 -0.0637745    -0.255412    0.045242     …   0.00848006    0.024504
 -0.672223     -0.0846755   0.0823317       -0.155654     -0.309793
  0.286397      0.256278    0.0976185       -0.696412      0.0146294
 -0.0154922     0.290553   -0.314116         0.579134      0.270772

In [21]:
maximum(randn(6, 9)*P*A)

2.0095036745715333e-14